services:
  - type: web
    name: sagor-bot
    env: node
    region: singapore
    plan: starter
    buildCommand: apt-get update -qq && apt-get install -y -qq libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev > /dev/null && npm install
    startCommand: node index.js
    healthCheckPath: /health
    autoDeploy: false

    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: sagor-bot
          type: web
          property: host
